### PR TITLE
Collaborative Project Cloning THE NEXT-WEB

### PR DESCRIPTION
**Pull request by JulianaOsemeke**
This is a replica of the The Next Web website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.

### CODE REVIEW

**Comment by Addis-Belete** [comment]
THE NEXT WEB

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: :red_circle: 
------------------
Hello!!@JulianaOsemeke @Addis0943 :wave:  You are doing g an amazing job on this milestone :clap: :muscle: 
However, there are a few changes to make to complete this milestone :hammer_and_wrench:  see them below :eyes: :point_down: 
----------------

- [x] Improve your commit summary message.
- Check your grammar with Grammarly, you have some errors in the grammar that make your pull request unprofessional. 
- Write a more descriptive summary message. You can write that you implemented the header, footer, highlights and  Latest funding that are responsive. [Here](https://microverse.zendesk.com/hc/en-us/articles/360055660814-Professional-GitHub-repository) you can read about how to write a meaningful summary. 
- You are not cloning a Perma website, you are cloning "The Next Web." website.

- [x] Improve your Readme. 
- As above :point_up_2:  you are not cloning "Parma" website. Please change the name to "he Next Web".
- In the section "To get local copy up and running follow these simple example steps". The steps are for another project, kindly change it. 
- [optional] put the commands inside this marks ` `` ` you gonna highlight the commands.

- [x] Please delete the image that you are not using "app_screenshot.png"
- [x] The logo must be a link `a` tag. 
- [x] On mobile there is a hamburger icon please add it. 
- [x] The hamburger button and the search button should be a link `a` tag. 
- [x] The highlights image titles, must be links `a` tag.
- [x] On desktop.
- There is a red overlay with a gradient in the top half of the first article
- The date appears over the first article, at the top right corner

- [x] Use the `nav` tag for the menus. You are using `div` instead. 
- [x] All the nav menus should be links `a` tags
-----------------
Please make the required changes :hammer_and_wrench: :point_up_2: and send it for another review. :smile: 
HAPPY CODING!!
MB5W4D

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

Hi @JulianaOsemeke and @Addis0943  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

### Header

#### All screen sizes
* [x] Use links (`a` tag) for all the menu options, the hamburger button and the search button

#### Mobile

* [x] There should be a hamburger (bars) icon at the rightmost part (next to the search icon). You have the text `menu` in place of the hamburger menu. Kindly fix that.

#### Desktop

* [x] The TNW logo disappears. The TNW logo at the top-left corner of the second navbar should only be present on mobile screen size.

### Highlights (top 3 articles)

#### All screen sizes

* [x] The title of each article is a header (`hx` tag) and has a link (`a` tag). Your articles do not have a link tag. Kindly add them.
* [x] Kindly increase the height of the highlights (first three articles).

### Latest Funding section

#### All screen sizes

* [x] The title of the section is a header (`hx` tag) and has a link (`a` tag).
* [x] The nav menu (See more, Get updates, etc.) are grouped in a `nav` tag and each one have links (`a` tag)
* [x] Each article has
  * [x] Its own title (`hx` tag) and has a link (`a` tag)
  * [x] Two categories items, with a link (`a` tag).
  * [x] A text excerpt at the bottom, that also has a link (`a` tag)

### Kindly make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by Addis-Belete** [comment]
Hey! Thank you for feedback. We have done all the changes requested. 
NB. The hamburger Icon is visible on our end.
Screen Shot 2013-06-17 at 4 53 19 PM

**Review by whiz25 — APPROVED** [review]
## Approved ✅ 
Nicely done. You made the requested changes. Please merge and proceed to the next project.

### Martin Afani

**Pull request merged**
